# Generated by Django 5.2.12 on 2026-04-02 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('hash', models.CharField(help_text='SHA-256 hash of the file content.', max_length=64, primary_key=True, serialize=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Initialization'), ('EXTRACTING', 'EXTRACTING (LlamaParse)'), ('EXTRACTION_FAILED', 'EXTRACTION_FAILED'), ('CHUNKING', 'CHUNKING'), ('CHUNKING_FAILED', 'CHUNKING_FAILED'), ('UPLOADING', 'UPLOADING'), ('UPLOAD_FAILED', 'UPLOAD_FAILED'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyAsset',
            fields=[
                ('sqlite_asset_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(default='EXTRACTED', help_text='EXTRACTED or UPLOADED', max_length=20)),
                ('asset_type', models.CharField(help_text="'text', 'table'", max_length=50)),
                ('content', models.TextField(help_text='Markdown text, or table')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_paths', models.JSONField(blank=True, default=list, help_text='List of associated image filenames')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.document')),
            ],
        ),
    ]
